#!/usr/bin/expect -f
set timeout 120
spawn ssh -o StrictHostKeyChecking=no root@187.77.140.205

expect {
    "password:" {
        send "\"-4V2HOvVFF,q7Bx2\"\r"
        exp_continue
    }
    "#" {
        send "cd ~/super_real_estate\r"
    }
}

expect "#"
send "git fetch origin v1\r"

expect "#"
send "git clean -fd\r"

expect "#"
send "git stash\r"

expect "#"
send "git checkout v1\r"

expect "#"
send "git pull origin v1\r"

expect "#"
send "docker restart super_backend super_frontend\r"

expect "#"
send "exit\r"
expect eof
