import React from 'react';
import { 
    MdKitchen, MdBathtub, MdTv, MdAir, MdMicrowave, MdLocalLaundryService, 
    MdShower, MdRestaurant, MdLocalParking, MdPool, MdFitnessCenter, MdSecurity, 
    MdHotTub, MdPark, MdChildCare, MdComputer, MdElevator, MdGroups, MdStore, 
    MdDirectionsBus, MdSpa, MdGarage, MdMeetingRoom, MdCheckCircleOutline,
    MdCoffeeMaker, MdTableBar, MdWeekend, MdKingBed, MdBed, MdDoorSliding,
    MdSensorDoor, MdDesk, MdChair, MdBalcony, MdDeck, MdRouter, MdVpnKey,
    MdSensors, MdFireExtinguisher, MdCurtainsClosed, MdPets, MdCleaningServices,
    MdStorage, MdOutdoorGrill, MdLocalLibrary, MdSelfImprovement, MdDirectionsRun,
    MdSportsBasketball, MdSportsTennis, MdSports, MdVideocam, MdFastfood,
    MdMarkunreadMailbox, MdBusinessCenter, MdCelebration, MdStorefront,
    MdLocalAtm, MdLocalPharmacy, MdLocalCafe, MdRoomService, MdLocalPostOffice,
    MdBorderOuter, MdApartment, MdLocationCity, MdWater, MdTerrain, MdLandscape,
    MdBrush, MdPublic, MdMonetizationOn, MdSubway, MdLocalAirport, MdDirectionsCar,
    MdLocalHospital, MdSchool, MdLocalGroceryStore, MdBeachAccess, MdCorporateFare,
    MdMap, MdEvStation, MdDirectionsBike, MdSportsEsports
} from 'react-icons/md';

// Generic fallback icon
const DefaultIcon = () => <MdCheckCircleOutline className="w-5 h-5 text-gray-400" />;

export const UNIT_AMENITIES = [
    { id: 'refrigerator', label: 'Refrigerator', icon: <MdKitchen className="w-5 h-5 text-blue-400" /> },
    { id: 'ac', label: 'Air Conditioning', icon: <MdAir className="w-5 h-5 text-cyan-400" /> },
    { id: 'water_heater', label: 'Water Heater', icon: <MdShower className="w-5 h-5 text-blue-400" /> },
    { id: 'bathtub', label: 'Bathtub', icon: <MdBathtub className="w-5 h-5 text-blue-300" /> },
    { id: 'microwave', label: 'Microwave', icon: <MdMicrowave className="w-5 h-5 text-orange-400" /> },
    { id: 'kitchen', label: 'Kitchen / Stove', icon: <MdRestaurant className="w-5 h-5 text-orange-500" /> },
    { id: 'tv', label: 'TV', icon: <MdTv className="w-5 h-5 text-gray-600" /> },
    { id: 'washing_machine', label: 'Washing Machine', icon: <MdLocalLaundryService className="w-5 h-5 text-gray-400" /> },
    { id: 'dishwasher', label: 'Dishwasher', icon: <MdCleaningServices className="w-5 h-5 text-teal-400" /> },
    { id: 'oven', label: 'Oven', icon: <MdMicrowave className="w-5 h-5 text-red-400" /> },
    { id: 'electric_kettle', label: 'Electric Kettle', icon: <MdCoffeeMaker className="w-5 h-5 text-amber-600" /> },
    { id: 'rice_cooker', label: 'Rice Cooker', icon: <MdKitchen className="w-5 h-5 text-amber-500" /> },
    { id: 'toaster', label: 'Toaster', icon: <MdMicrowave className="w-5 h-5 text-orange-300" /> },
    { id: 'coffee_machine', label: 'Coffee Machine', icon: <MdCoffeeMaker className="w-5 h-5 text-amber-850" /> },
    { id: 'dining_table', label: 'Dining Table', icon: <MdTableBar className="w-5 h-5 text-amber-700" /> },
    { id: 'sofa', label: 'Sofa', icon: <MdWeekend className="w-5 h-5 text-red-400" /> },
    { id: 'bed_frame', label: 'Bed Frame', icon: <MdKingBed className="w-5 h-5 text-amber-600" /> },
    { id: 'mattress', label: 'Mattress', icon: <MdBed className="w-5 h-5 text-blue-400" /> },
    { id: 'wardrobe', label: 'Wardrobe', icon: <MdDoorSliding className="w-5 h-5 text-gray-500" /> },
    { id: 'walk_in_closet', label: 'Walk-in Closet', icon: <MdSensorDoor className="w-5 h-5 text-gray-600" /> },
    { id: 'work_desk', label: 'Work Desk', icon: <MdDesk className="w-5 h-5 text-amber-700" /> },
    { id: 'office_chair', label: 'Office Chair', icon: <MdChair className="w-5 h-5 text-gray-750" /> },
    { id: 'balcony', label: 'Balcony', icon: <MdBalcony className="w-5 h-5 text-sky-500" /> },
    { id: 'private_terrace', label: 'Private Terrace', icon: <MdDeck className="w-5 h-5 text-amber-600" /> },
    { id: 'smart_tv', label: 'Smart TV', icon: <MdTv className="w-5 h-5 text-indigo-600" /> },
    { id: 'high_speed_internet', label: 'High-Speed Internet', icon: <MdRouter className="w-5 h-5 text-blue-500" /> },
    { id: 'wifi_router', label: 'Wi-Fi Router', icon: <MdRouter className="w-5 h-5 text-cyan-500" /> },
    { id: 'cable_tv', label: 'Cable TV', icon: <MdTv className="w-5 h-5 text-slate-500" /> },
    { id: 'digital_door_lock', label: 'Digital Door Lock', icon: <MdVpnKey className="w-5 h-5 text-amber-500" /> },
    { id: 'smoke_detector', label: 'Smoke Detector', icon: <MdSensors className="w-5 h-5 text-red-500" /> },
    { id: 'fire_extinguisher', label: 'Fire Extinguisher', icon: <MdFireExtinguisher className="w-5 h-5 text-red-600" /> },
    { id: 'blackout_curtains', label: 'Blackout Curtains', icon: <MdCurtainsClosed className="w-5 h-5 text-slate-600" /> },
    { id: 'pet_friendly', label: 'Pet Friendly', icon: <MdPets className="w-5 h-5 text-orange-400" /> },
    { id: 'maid_room', label: 'Maid Room', icon: <MdCleaningServices className="w-5 h-5 text-teal-500" /> },
    { id: 'storage_room', label: 'Storage Room', icon: <MdStorage className="w-5 h-5 text-slate-500" /> },
];

export const BUILDING_FEATURES = [
    { id: 'covered_car_park', label: 'Covered Car Park', icon: <MdLocalParking className="w-5 h-5 text-blue-500" /> },
    { id: 'swimming_pool', label: 'Swimming Pool', icon: <MdPool className="w-5 h-5 text-cyan-500" /> },
    { id: 'fitness_gym', label: 'Fitness / Gym', icon: <MdFitnessCenter className="w-5 h-5 text-gray-700" /> },
    { id: 'security_24h', label: '24h Security', icon: <MdSecurity className="w-5 h-5 text-red-500" /> },
    { id: 'sauna', label: 'Sauna', icon: <MdHotTub className="w-5 h-5 text-orange-400" /> },
    { id: 'garden_bbq', label: 'Garden / BBQ', icon: <MdOutdoorGrill className="w-5 h-5 text-orange-650" /> },
    { id: 'playground', label: 'Playground', icon: <MdChildCare className="w-5 h-5 text-purple-400" /> },
    { id: 'coworking_space', label: 'Co-working Space', icon: <MdComputer className="w-5 h-5 text-gray-650" /> },
    { id: 'library', label: 'Library / Reading Room', icon: <MdLocalLibrary className="w-5 h-5 text-amber-700" /> },
    { id: 'yoga_room', label: 'Yoga Room', icon: <MdSelfImprovement className="w-5 h-5 text-teal-650" /> },
    { id: 'steam_room', label: 'Steam Room', icon: <MdHotTub className="w-5 h-5 text-sky-400" /> },
    { id: 'jogging_track', label: 'Jogging Track', icon: <MdDirectionsRun className="w-5 h-5 text-emerald-500" /> },
    { id: 'basketball_court', label: 'Basketball Court', icon: <MdSportsBasketball className="w-5 h-5 text-orange-500" /> },
    { id: 'tennis_court', label: 'Tennis Court', icon: <MdSportsTennis className="w-5 h-5 text-green-500" /> },
    { id: 'badminton_court', label: 'Badminton Court', icon: <MdSports className="w-5 h-5 text-sky-500" /> },
    { id: 'rooftop_garden', label: 'Rooftop Garden', icon: <MdPark className="w-5 h-5 text-emerald-600" /> },
    { id: 'sky_lounge', label: 'Sky Lounge', icon: <MdLocalCafe className="w-5 h-5 text-violet-500" /> },
    { id: 'meeting_room', label: 'Meeting Room', icon: <MdMeetingRoom className="w-5 h-5 text-blue-700" /> },
    { id: 'private_lounge', label: 'Private Lounge', icon: <MdWeekend className="w-5 h-5 text-purple-600" /> },
    { id: 'kids_room', label: 'Kids Room', icon: <MdChildCare className="w-5 h-5 text-pink-400" /> },
    { id: 'pet_area', label: 'Pet Area', icon: <MdPets className="w-5 h-5 text-orange-400" /> },
    { id: 'ev_charging_station', label: 'EV Charging Station', icon: <MdEvStation className="w-5 h-5 text-green-500" /> },
    { id: 'bicycle_parking', label: 'Bicycle Parking', icon: <MdDirectionsBike className="w-5 h-5 text-teal-500" /> },
    { id: 'cctv_monitoring', label: 'CCTV Monitoring', icon: <MdVideocam className="w-5 h-5 text-slate-500" /> },
    { id: 'key_card_access', label: 'Key Card Access', icon: <MdVpnKey className="w-5 h-5 text-amber-500" /> },
    { id: 'shuttle_service', label: 'Shuttle Service', icon: <MdDirectionsBus className="w-5 h-5 text-blue-500" /> },
    { id: 'laundry_room', label: 'Laundry Room', icon: <MdLocalLaundryService className="w-5 h-5 text-gray-400" /> },
    { id: 'convenience_store', label: 'Convenience Store', icon: <MdStore className="w-5 h-5 text-emerald-600" /> },
    { id: 'parcel_locker', label: 'Parcel Locker', icon: <MdMarkunreadMailbox className="w-5 h-5 text-indigo-500" /> },
    { id: 'vending_machine', label: 'Vending Machine', icon: <MdFastfood className="w-5 h-5 text-orange-400" /> },
];

export const PROJECT_FACILITIES = [
    { id: 'communal_elevator', label: 'Communal Elevator', icon: <MdElevator className="w-5 h-5 text-gray-500" /> },
    { id: 'communal_reception', label: 'Communal Reception', icon: <MdGroups className="w-5 h-5 text-amber-600" /> },
    { id: 'communal_restaurant', label: 'Communal Restaurant', icon: <MdRestaurant className="w-5 h-5 text-orange-500" /> },
    { id: 'communal_shop', label: 'Communal Shop', icon: <MdStore className="w-5 h-5 text-emerald-600" /> },
    { id: 'communal_shuttle', label: 'Communal Shuttle Service', icon: <MdDirectionsBus className="w-5 h-5 text-blue-500" /> },
    { id: 'communal_spa', label: 'Communal Spa', icon: <MdSpa className="w-5 h-5 text-pink-400" /> },
    { id: 'communal_coworking', label: 'Communal Coworking Space', icon: <MdComputer className="w-5 h-5 text-gray-600" /> },
    { id: 'communal_security_24', label: 'Communal Security 24 Hours', icon: <MdSecurity className="w-5 h-5 text-red-500" /> },
    { id: 'communal_parking', label: 'Communal Car Park', icon: <MdLocalParking className="w-5 h-5 text-blue-500" /> },
    { id: 'communal_covered_parking', label: 'Communal Covered Car Park', icon: <MdGarage className="w-5 h-5 text-blue-600" /> },
    { id: 'communal_function_room', label: 'Communal Function Room', icon: <MdMeetingRoom className="w-5 h-5 text-amber-700" /> },
    { id: 'business_center', label: 'Business Center', icon: <MdBusinessCenter className="w-5 h-5 text-indigo-650" /> },
    { id: 'conference_room', label: 'Conference Room', icon: <MdGroups className="w-5 h-5 text-blue-650" /> },
    { id: 'event_hall', label: 'Event Hall', icon: <MdCelebration className="w-5 h-5 text-purple-500" /> },
    { id: 'wedding_hall', label: 'Wedding Hall', icon: <MdCelebration className="w-5 h-5 text-pink-500" /> },
    { id: 'childrens_play_area', label: "Children's Play Area", icon: <MdChildCare className="w-5 h-5 text-teal-400" /> },
    { id: 'indoor_recreation_room', label: 'Indoor Recreation Room', icon: <MdSportsEsports className="w-5 h-5 text-indigo-500" /> },
    { id: 'outdoor_recreation_area', label: 'Outdoor Recreation Area', icon: <MdPark className="w-5 h-5 text-emerald-500" /> },
    { id: 'mini_mart', label: 'Mini Mart', icon: <MdStorefront className="w-5 h-5 text-amber-600" /> },
    { id: 'atm_service', label: 'ATM Service', icon: <MdLocalAtm className="w-5 h-5 text-green-600" /> },
    { id: 'pharmacy', label: 'Pharmacy', icon: <MdLocalPharmacy className="w-5 h-5 text-red-500" /> },
    { id: 'cafe', label: 'Cafe', icon: <MdLocalCafe className="w-5 h-5 text-amber-800" /> },
    { id: 'food_court', label: 'Food Court', icon: <MdFastfood className="w-5 h-5 text-orange-500" /> },
    { id: 'beauty_salon', label: 'Beauty Salon', icon: <MdSpa className="w-5 h-5 text-rose-400" /> },
    { id: 'housekeeping_service', label: 'Housekeeping Service', icon: <MdCleaningServices className="w-5 h-5 text-sky-500" /> },
    { id: 'concierge_service', label: 'Concierge Service', icon: <MdRoomService className="w-5 h-5 text-blue-600" /> },
    { id: 'parcel_collection_point', label: 'Parcel Collection Point', icon: <MdLocalPostOffice className="w-5 h-5 text-indigo-500" /> },
    { id: 'visitor_parking', label: 'Visitor Parking', icon: <MdLocalParking className="w-5 h-5 text-cyan-600" /> },
    { id: 'ev_charging_area', label: 'EV Charging Area', icon: <MdEvStation className="w-5 h-5 text-emerald-500" /> },
];

export const PROPERTY_FEATURES = [
    { id: 'corner_unit', label: 'Corner Unit', icon: <MdBorderOuter className="w-5 h-5 text-blue-500" /> },
    { id: 'high_floor', label: 'High Floor', icon: <MdApartment className="w-5 h-5 text-sky-500" /> },
    { id: 'low_floor', label: 'Low Floor', icon: <MdApartment className="w-5 h-5 text-slate-500" /> },
    { id: 'city_view', label: 'City View', icon: <MdLocationCity className="w-5 h-5 text-indigo-500" /> },
    { id: 'river_view', label: 'River View', icon: <MdWater className="w-5 h-5 text-blue-400" /> },
    { id: 'pool_view', label: 'Pool View', icon: <MdPool className="w-5 h-5 text-cyan-400" /> },
    { id: 'garden_view', label: 'Garden View', icon: <MdPark className="w-5 h-5 text-emerald-500" /> },
    { id: 'mountain_view', label: 'Mountain View', icon: <MdTerrain className="w-5 h-5 text-green-600" /> },
    { id: 'sea_view', label: 'Sea View', icon: <MdWater className="w-5 h-5 text-sky-500" /> },
    { id: 'fully_furnished', label: 'Fully Furnished', icon: <MdWeekend className="w-5 h-5 text-amber-600" /> },
    { id: 'partially_furnished', label: 'Partially Furnished', icon: <MdChair className="w-5 h-5 text-amber-500" /> },
    { id: 'unfurnished', label: 'Unfurnished', icon: <MdApartment className="w-5 h-5 text-gray-400" /> },
    { id: 'newly_renovated', label: 'Newly Renovated', icon: <MdBrush className="w-5 h-5 text-violet-500" /> },
    { id: 'ready_to_move_in', label: 'Ready To Move In', icon: <MdApartment className="w-5 h-5 text-emerald-500" /> },
    { id: 'foreign_quota_available', label: 'Foreign Quota Available', icon: <MdPublic className="w-5 h-5 text-teal-500" /> },
    { id: 'freehold', label: 'Freehold', icon: <MdVpnKey className="w-5 h-5 text-amber-650" /> },
    { id: 'leasehold', label: 'Leasehold', icon: <MdVpnKey className="w-5 h-5 text-slate-400" /> },
    { id: 'owner_occupied', label: 'Owner Occupied', icon: <MdApartment className="w-5 h-5 text-blue-600" /> },
    { id: 'investment_property', label: 'Investment Property', icon: <MdMonetizationOn className="w-5 h-5 text-green-600" /> },
];

export const NEARBY_PLACES = [
    { id: 'bts_nearby', label: 'BTS Nearby', icon: <MdSubway className="w-5 h-5 text-green-650" /> },
    { id: 'mrt_nearby', label: 'MRT Nearby', icon: <MdSubway className="w-5 h-5 text-blue-650" /> },
    { id: 'airport_nearby', label: 'Airport Nearby', icon: <MdLocalAirport className="w-5 h-5 text-sky-500" /> },
    { id: 'expressway_nearby', label: 'Expressway Nearby', icon: <MdDirectionsCar className="w-5 h-5 text-orange-500" /> },
    { id: 'shopping_mall_nearby', label: 'Shopping Mall Nearby', icon: <MdStorefront className="w-5 h-5 text-indigo-650" /> },
    { id: 'hospital_nearby', label: 'Hospital Nearby', icon: <MdLocalHospital className="w-5 h-5 text-red-500" /> },
    { id: 'international_school_nearby', label: 'International School Nearby', icon: <MdSchool className="w-5 h-5 text-amber-600" /> },
    { id: 'university_nearby', label: 'University Nearby', icon: <MdSchool className="w-5 h-5 text-violet-650" /> },
    { id: 'supermarket_nearby', label: 'Supermarket Nearby', icon: <MdLocalGroceryStore className="w-5 h-5 text-emerald-600" /> },
    { id: 'public_park_nearby', label: 'Public Park Nearby', icon: <MdPark className="w-5 h-5 text-green-500" /> },
    { id: 'office_district_nearby', label: 'Office District Nearby', icon: <MdCorporateFare className="w-5 h-5 text-slate-600" /> },
    { id: 'night_market_nearby', label: 'Night Market Nearby', icon: <MdStorefront className="w-5 h-5 text-purple-650" /> },
    { id: 'beach_nearby', label: 'Beach Nearby', icon: <MdBeachAccess className="w-5 h-5 text-amber-500" /> },
    { id: 'tourist_attraction_nearby', label: 'Tourist Attraction Nearby', icon: <MdMap className="w-5 h-5 text-rose-500" /> },
];
