#!/usr/bin/expect -f
set timeout 600
set password "-4V2HOvVFF,q7Bx2"
spawn ssh -o StrictHostKeyChecking=no root@srv1534108.hstgr.cloud
expect "password:"
send -- "$password\r"
expect "# "
send "cd super_real_estate\r"
expect "# "
send "git fetch origin v1\r"
expect "# "
send "git checkout v1\r"
expect "# "
send "git pull origin v1\r"
expect "# "
send "docker compose up -d --build\r"
expect {
    "#" { send "exit\r" }
    timeout { send "\x03"; exit }
}
interact
